In [2]:
import pandas as pd

In [3]:
#Import CSV and convert to Pandas DataFrame

airbnb_df = pd.read_csv('Airbnb_Open_Data.csv')
airbnb_df.head()

C:\Users\Manro\AppData\Local\Temp\ipykernel_23048\1977381797.py:3: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  airbnb_df = pd.read_csv('Airbnb_Open_Data.csv')

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [4]:
#Clear out unnecessary coulmns

airbnb_df = airbnb_df.drop(['host id', 'host_identity_verified', 'host name', 'country', 'country code', 'availability 365',
                           'minimum nights', 'last review'], axis=1)
airbnb_df.head()

,id,NAME,neighbourhood group,neighbourhood,lat,long,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,number of reviews,reviews per month,review rate number,calculated host listings count,house_rules,license
0,1001254,Clean & quiet apt home by the park,Brooklyn,Kensington,40.64749,-73.97237,False,strict,Private room,2020.0,$966,$193,9.0,0.21,4.0,6.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,Manhattan,Midtown,40.75362,-73.98377,False,moderate,Entire home/apt,2007.0,$142,$28,45.0,0.38,4.0,2.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,Manhattan,Harlem,40.80902,-73.94190,True,flexible,Private room,2005.0,$620,$124,0.0,NaN,5.0,1.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,Brooklyn,Clinton Hill,40.68514,-73.95976,True,moderate,Entire home/apt,2005.0,$368,$74,270.0,4.64,4.0,1.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,Manhattan,East Harlem,40.79851,-73.94399,False,moderate,Entire home/apt,2009.0,$204,$41,9.0,0.10,3.0,1.0,"Please no smoking in the house, porch or on th...",NaN

In [5]:
# Check neighbourhood group' for any errors

hood_values = airbnb_df['neighbourhood group'].unique()
value_counts = airbnb_df['neighbourhood group'].value_counts()
print(hood_values)
print('-----------------')
print(value_counts)

['Brooklyn' 'Manhattan' 'brookln' 'manhatan' 'Queens' nan 'Staten Island'
 'Bronx']
-----------------
Manhattan        43792
Brooklyn         41842
Queens           13267
Bronx             2712
Staten Island      955
brookln              1
manhatan             1
Name: neighbourhood group, dtype: int64

In [6]:
#Change 'brookln' to Brooklyn

brookln = airbnb_df.loc[airbnb_df['neighbourhood group']=='brookln']
airnbn_df = airbnb_df.loc[brookln.index, 'neighbourhood group'] = 'Brooklyn' 

#Change 'manhatan' to Manhattan

manhatan = airbnb_df.loc[airbnb_df['neighbourhood group']=='manhatan']
airnbn_df = airbnb_df.loc[manhatan.index, 'neighbourhood group'] = 'Manhattan'

In [7]:
#Make sure the values have been changed

new_hood_values = airbnb_df['neighbourhood group'].unique()
new_value_counts = airbnb_df['neighbourhood group'].value_counts()
print(new_hood_values)
print('-----------------------------------------------------------------------')
print(new_value_counts)

['Brooklyn' 'Manhattan' 'Queens' nan 'Staten Island' 'Bronx']
-----------------------------------------------------------------------
Manhattan        43793
Brooklyn         41843
Queens           13267
Bronx             2712
Staten Island      955
Name: neighbourhood group, dtype: int64

In [8]:
#Change column names

airbnb_df = airbnb_df.rename(columns={
    'NAME': 'Name',
    'neighbourhood group': 'Borough',
    'neighbourhood': 'Neighbourhood',
    'lat': 'Lat',
    'long': 'Lon',
    'instant_bookable': 'Instant Booking',
    'cancellation_policy': 'Cancellation Policy',
    'room type': 'Room Type',
    'Construction year': 'Construction Year',
    'price': 'Price Per Night',
    'service fee': 'Service Fee',
    'number of reviews': 'Total Reviews',
    'reviews per month': 'Reviews Per Month',
    'review rate number': 'Review Rate Number',
    'calculated host listings count': 'Host Listings Count',
    'house_rules': 'House Rules',
    'license': 'License'
})

airbnb_df.head()

,id,Name,Borough,Neighbourhood,Lat,Lon,Instant Booking,Cancellation Policy,Room Type,Construction Year,Price Per Night,Service Fee,Total Reviews,Reviews Per Month,Review Rate Number,Host Listings Count,House Rules,License
0,1001254,Clean & quiet apt home by the park,Brooklyn,Kensington,40.64749,-73.97237,False,strict,Private room,2020.0,$966,$193,9.0,0.21,4.0,6.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,Manhattan,Midtown,40.75362,-73.98377,False,moderate,Entire home/apt,2007.0,$142,$28,45.0,0.38,4.0,2.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,Manhattan,Harlem,40.80902,-73.94190,True,flexible,Private room,2005.0,$620,$124,0.0,NaN,5.0,1.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,Brooklyn,Clinton Hill,40.68514,-73.95976,True,moderate,Entire home/apt,2005.0,$368,$74,270.0,4.64,4.0,1.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,Manhattan,East Harlem,40.79851,-73.94399,False,moderate,Entire home/apt,2009.0,$204,$41,9.0,0.10,3.0,1.0,"Please no smoking in the house, porch or on th...",NaN

In [9]:
#Check data types are usable for analysis

data_types = airbnb_df.dtypes
print(data_types)

id                       int64
Name                    object
Borough                 object
Neighbourhood           object
Lat                    float64
Lon                    float64
Instant Booking         object
Cancellation Policy     object
Room Type               object
Construction Year      float64
Price Per Night         object
Service Fee             object
Total Reviews          float64
Reviews Per Month      float64
Review Rate Number     float64
Host Listings Count    float64
House Rules             object
License                 object
dtype: object

In [10]:
airbnb_df.to_csv("LearnPython/airbnb.csv", index=False)

OSError: Cannot save file into a non-existent directory: 'LearnPython'